### ISSUE TITLE
Grid size

### ISSUE THREAD

**Issue by IanaKhitsko** [3A43Mka/euro-diffusion#3]
https://github.com/3A43Mka/euro-diffusion/blob/3a601bb4b33afe8d96a0e1b99e1d61b8d7ece1d6/src/map.js#L8

Why do we need extended grid size (you are adding +1 here ) ?

**Comment by 3A43Mka** [comment]
The task says that coordinates start from 1 and the last value is 10. But in JS and in many other languages arrays start from 0. In order to not care about translating coordiantes after reading there from files and make life easier, we can create a grid in which we can count from 1 to 10 indexes, If we create grid of size of 10, then we can only traverse from 0 to 9 by indexes, so we would need to translate coords to match "physical" coords and "array-like" indexes. So we just create 11*11 and don't use the edge and we can work in [1...10] index range without caring about going out of range. And this also doesn't make us any problems in the context of this task.
